apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fullstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Fullstack cloud-native application

  sourceRepos:
    - https://github.com/jaosullivan/webapp

  destinations:
    - namespace: fullstack
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  # Allow creating Namespace at cluster scope
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: networking.k8s.io
      kind: Ingress

  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
