---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: users-pdb
  namespace: fullstack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: users

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders-pdb
  namespace: fullstack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: orders

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payments-pdb
  namespace: fullstack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payments

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: fullstack
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
